# Generated by Django 4.2.3 on 2023-07-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
